-- ============================================================================
-- HebaTech — carga inicial do catálogo
--
-- Gerado por `npm run carga-sql`. Não edite à mão.
--
-- Como usar: Supabase → SQL Editor → cole este arquivo inteiro → Run.
-- Rode DEPOIS do supabase/schema.sql.
--
-- Pode colar de novo sem duplicar nada: produto com o mesmo código é
-- atualizado. Mas atenção — colar de novo devolve preço, texto e
-- disponibilidade ao valor de fábrica. Depois que a loja começar a editar pelo
-- painel, não cole mais. Foto enviada pelo painel é sempre preservada.
-- ============================================================================

-- ── 19 produtos ──
insert into public.produtos (codigo, slug, categoria, marca, modelo, condicao, preco, preco_referencia, destaque, disponivel, resumo, cpu_familia, cpu_nome, ram_gb, armazenamento_gb, armazenamento_tipo, tela_polegadas, tela_resolucao, bateria_saude, peso_kg, ficha, estado_grau, estado_observacoes, garantia_dias, ordem)
values
  ('HT-L5490', 'dell-latitude-5490-i5-8gb-256gb', 'notebook', 'Dell', 'Latitude 5490', 'seminovo', 1590, 1890, true, true, 'Chassi sem trincas, tela sem pixel morto, dobradiças firmes.', 'i5', 'Intel Core i5-8350U', 8, 256, 'NVMe', 14, '1920 x 1080', 84, 1.63, '[{"rotulo":"Processador","valor":"Intel Core i5-8350U · 4 núcleos / 8 threads"},{"rotulo":"Clock","valor":"1.7 GHz base · 3.6 GHz turbo"},{"rotulo":"Memória","valor":"8 GB DDR4 2400 MHz"},{"rotulo":"Expansão de memória","valor":"2 slots SODIMM — 1 ocupado, expansível até 32 GB"},{"rotulo":"Armazenamento","valor":"256 GB SSD NVMe M.2"},{"rotulo":"Expansão de disco","valor":"Baia 2.5\" livre para HD adicional"},{"rotulo":"Tela","valor":"14\" 1920 x 1080 IPS · antirreflexo"},{"rotulo":"Vídeo","valor":"Intel UHD Graphics 620 (integrado)"},{"rotulo":"Bateria","valor":"3 células, 51 Wh · 84% de saúde · 4h a 5h em uso de escritório"},{"rotulo":"Teclado","valor":"ABNT2 retroiluminado"},{"rotulo":"Rede","valor":"Wi-Fi 5 (ac) + Bluetooth 4.2"},{"rotulo":"Conexões","valor":"2x USB 3.1 Type-A · USB-C com DisplayPort · HDMI 1.4 · RJ-45 Gigabit · Leitor SD · Combo P2"},{"rotulo":"Sistema","valor":"Windows 11 Pro ativado"},{"rotulo":"Peso","valor":"1.63 kg"}]'::jsonb, 'A', '["Marcas leves de uso na tampa, visíveis apenas contra a luz","Teclado sem brilho de desgaste nas teclas centrais","Bateria original, 84% de saúde medida no diagnóstico"]'::jsonb, 90, 0),
  ('HT-T480', 'lenovo-thinkpad-t480-i5-16gb-512gb', 'notebook', 'Lenovo', 'ThinkPad T480', 'seminovo', 2190, 2490, true, true, 'Troca a quente de bateria funcionando, leitor biométrico testado.', 'i5', 'Intel Core i5-8250U', 16, 512, 'NVMe', 14, '1920 x 1080', 91, 1.58, '[{"rotulo":"Processador","valor":"Intel Core i5-8250U · 4 núcleos / 8 threads"},{"rotulo":"Clock","valor":"1.6 GHz base · 3.4 GHz turbo"},{"rotulo":"Memória","valor":"16 GB DDR4 2400 MHz"},{"rotulo":"Expansão de memória","valor":"2 slots SODIMM — 2 ocupados (8+8)"},{"rotulo":"Armazenamento","valor":"512 GB SSD NVMe M.2"},{"rotulo":"Expansão de disco","valor":"1 slot M.2 2242 livre"},{"rotulo":"Tela","valor":"14\" 1920 x 1080 IPS · antirreflexo"},{"rotulo":"Vídeo","valor":"Intel UHD Graphics 620 (integrado)"},{"rotulo":"Bateria","valor":"Sistema duplo: interna 24 Wh + externa 24 Wh · 91% de saúde · 7h a 9h em uso de escritório"},{"rotulo":"Teclado","valor":"ABNT2 retroiluminado com TrackPoint"},{"rotulo":"Rede","valor":"Wi-Fi 5 (ac) + Bluetooth 4.2"},{"rotulo":"Conexões","valor":"2x USB 3.1 Type-A · 2x USB-C (1 Thunderbolt 3) · HDMI 1.4 · RJ-45 Gigabit · Leitor microSD · Combo P2"},{"rotulo":"Sistema","valor":"Windows 11 Pro ativado"},{"rotulo":"Peso","valor":"1.58 kg"}]'::jsonb, 'A', '["Ambas as baterias substituídas por novas na revisão","Base emborrachada íntegra, sem descascado","Tampa com um risco fino de 2 cm no canto inferior direito"]'::jsonb, 90, 1),
  ('HT-E840G5', 'hp-elitebook-840-g5-i5-8gb-256gb', 'notebook', 'HP', 'EliteBook 840 G5', 'seminovo', 1790, null, true, true, 'Funcional em tudo, com desgaste estético visível no apoio de mão.', 'i5', 'Intel Core i5-8250U', 8, 256, 'NVMe', 14, '1920 x 1080', 79, 1.48, '[{"rotulo":"Processador","valor":"Intel Core i5-8250U · 4 núcleos / 8 threads"},{"rotulo":"Clock","valor":"1.6 GHz base · 3.4 GHz turbo"},{"rotulo":"Memória","valor":"8 GB DDR4 2400 MHz"},{"rotulo":"Expansão de memória","valor":"2 slots SODIMM — 1 ocupado, expansível até 32 GB"},{"rotulo":"Armazenamento","valor":"256 GB SSD NVMe M.2"},{"rotulo":"Expansão de disco","valor":"Sem baia adicional"},{"rotulo":"Tela","valor":"14\" 1920 x 1080 IPS · antirreflexo"},{"rotulo":"Vídeo","valor":"Intel UHD Graphics 620 (integrado)"},{"rotulo":"Bateria","valor":"3 células, 50 Wh · 79% de saúde · 4h a 6h em uso de escritório"},{"rotulo":"Teclado","valor":"ABNT2 retroiluminado, resistente a respingos"},{"rotulo":"Rede","valor":"Wi-Fi 5 (ac) + Bluetooth 4.2"},{"rotulo":"Conexões","valor":"2x USB 3.1 Type-A · 2x USB-C Thunderbolt 3 · HDMI 1.4 · RJ-45 Gigabit · Combo P2"},{"rotulo":"Sistema","valor":"Windows 11 Pro ativado"},{"rotulo":"Peso","valor":"1.48 kg"}]'::jsonb, 'B', '["Brilho de uso no descanso de pulso do lado esquerdo","Moldura da tela com um ponto de tinta lascada","Bateria em 79% — troca opcional por R$ 320 no ato da compra"]'::jsonb, 90, 2),
  ('HT-L7490', 'dell-latitude-7490-i7-16gb-512gb', 'notebook', 'Dell', 'Latitude 7490', 'seminovo', 2690, null, true, true, 'Aparelho de lote corporativo com pouco uso, chassi de carbono íntegro.', 'i7', 'Intel Core i7-8650U', 16, 512, 'NVMe', 14, '1920 x 1080', 88, 1.4, '[{"rotulo":"Processador","valor":"Intel Core i7-8650U · 4 núcleos / 8 threads"},{"rotulo":"Clock","valor":"1.9 GHz base · 4.2 GHz turbo"},{"rotulo":"Memória","valor":"16 GB DDR4 2400 MHz"},{"rotulo":"Expansão de memória","valor":"2 slots SODIMM — 2 ocupados (8+8)"},{"rotulo":"Armazenamento","valor":"512 GB SSD NVMe M.2"},{"rotulo":"Expansão de disco","valor":"Sem baia adicional"},{"rotulo":"Tela","valor":"14\" 1920 x 1080 IPS · antirreflexo"},{"rotulo":"Vídeo","valor":"Intel UHD Graphics 620 (integrado)"},{"rotulo":"Bateria","valor":"4 células, 60 Wh · 88% de saúde · 6h a 8h em uso de escritório"},{"rotulo":"Teclado","valor":"ABNT2 retroiluminado"},{"rotulo":"Rede","valor":"Wi-Fi 5 (ac) + Bluetooth 4.2"},{"rotulo":"Conexões","valor":"2x USB 3.1 Type-A · 2x USB-C Thunderbolt 3 · HDMI 1.4 · RJ-45 Gigabit · Leitor microSD · Combo P2"},{"rotulo":"Sistema","valor":"Windows 11 Pro ativado"},{"rotulo":"Peso","valor":"1.40 kg"}]'::jsonb, 'A', '["Sem marcas de uso no apoio de mão","Leitor de digital e câmera testados","Pasta térmica trocada na revisão"]'::jsonb, 90, 3),
  ('HT-T14G1', 'lenovo-thinkpad-t14-gen1-i5-16gb-512gb', 'notebook', 'Lenovo', 'ThinkPad T14 Gen 1', 'seminovo', 2990, null, false, true, 'O mais novo do estoque. Praticamente sem sinal de uso.', 'i5', 'Intel Core i5-10310U', 16, 512, 'NVMe', 14, '1920 x 1080', 93, 1.55, '[{"rotulo":"Processador","valor":"Intel Core i5-10310U · 4 núcleos / 8 threads"},{"rotulo":"Clock","valor":"1.7 GHz base · 4.4 GHz turbo"},{"rotulo":"Memória","valor":"16 GB DDR4 2666 MHz"},{"rotulo":"Expansão de memória","valor":"8 GB soldados + 1 slot com 8 GB"},{"rotulo":"Armazenamento","valor":"512 GB SSD NVMe M.2"},{"rotulo":"Expansão de disco","valor":"Sem baia adicional"},{"rotulo":"Tela","valor":"14\" 1920 x 1080 IPS · antirreflexo"},{"rotulo":"Vídeo","valor":"Intel UHD Graphics (integrado)"},{"rotulo":"Bateria","valor":"3 células, 50 Wh · 93% de saúde · 8h a 10h em uso de escritório"},{"rotulo":"Teclado","valor":"ABNT2 retroiluminado com TrackPoint"},{"rotulo":"Rede","valor":"Wi-Fi 6 (ax) + Bluetooth 5.1"},{"rotulo":"Conexões","valor":"2x USB 3.2 Type-A · 2x USB-C (1 Thunderbolt 3) · HDMI 2.0 · RJ-45 Gigabit · Combo P2"},{"rotulo":"Sistema","valor":"Windows 11 Pro ativado"},{"rotulo":"Peso","valor":"1.55 kg"}]'::jsonb, 'A', '["Tampa e base sem riscos perceptíveis","Bateria em 93% de saúde","Acompanha carregador USB-C original de 65 W"]'::jsonb, 90, 4),
  ('HT-P640G4', 'hp-probook-640-g4-i5-8gb-256gb', 'notebook', 'HP', 'ProBook 640 G4', 'seminovo', 1490, null, false, true, 'Opção de entrada. Cumpre bem tarefa de escritório e sistema web.', 'i5', 'Intel Core i5-8250U', 8, 256, 'SATA', 14, '1366 x 768', 76, 1.75, '[{"rotulo":"Processador","valor":"Intel Core i5-8250U · 4 núcleos / 8 threads"},{"rotulo":"Clock","valor":"1.6 GHz base · 3.4 GHz turbo"},{"rotulo":"Memória","valor":"8 GB DDR4 2400 MHz"},{"rotulo":"Expansão de memória","valor":"2 slots SODIMM — 1 ocupado, expansível até 32 GB"},{"rotulo":"Armazenamento","valor":"256 GB SSD SATA M.2"},{"rotulo":"Expansão de disco","valor":"Baia 2.5\" livre para HD adicional"},{"rotulo":"Tela","valor":"14\" 1366 x 768 TN · antirreflexo"},{"rotulo":"Vídeo","valor":"Intel UHD Graphics 620 (integrado)"},{"rotulo":"Bateria","valor":"3 células, 48 Wh · 76% de saúde · 3h a 4h em uso de escritório"},{"rotulo":"Teclado","valor":"ABNT2 sem retroiluminação"},{"rotulo":"Rede","valor":"Wi-Fi 5 (ac) + Bluetooth 4.2"},{"rotulo":"Conexões","valor":"3x USB 3.1 Type-A · USB-C · HDMI 1.4 · VGA · RJ-45 Gigabit · Combo P2"},{"rotulo":"Sistema","valor":"Windows 11 Pro ativado"},{"rotulo":"Peso","valor":"1.75 kg"}]'::jsonb, 'B', '["Tela HD com ângulo de visão limitado — confira pessoalmente na loja","Riscos leves espalhados na tampa","Bateria em 76% — recomendamos uso com carregador na mesa"]'::jsonb, 90, 5),
  ('HT-L5400', 'dell-latitude-5400-i5-16gb-256gb', 'notebook', 'Dell', 'Latitude 5400', 'seminovo', 1990, null, false, true, 'Bateria de 68 Wh, boa autonomia para quem trabalha fora do escritório.', 'i5', 'Intel Core i5-8365U', 16, 256, 'NVMe', 14, '1920 x 1080', 85, 1.6, '[{"rotulo":"Processador","valor":"Intel Core i5-8365U · 4 núcleos / 8 threads"},{"rotulo":"Clock","valor":"1.6 GHz base · 4.1 GHz turbo"},{"rotulo":"Memória","valor":"16 GB DDR4 2666 MHz"},{"rotulo":"Expansão de memória","valor":"2 slots SODIMM — 2 ocupados (8+8)"},{"rotulo":"Armazenamento","valor":"256 GB SSD NVMe M.2"},{"rotulo":"Expansão de disco","valor":"1 slot M.2 livre"},{"rotulo":"Tela","valor":"14\" 1920 x 1080 IPS · antirreflexo"},{"rotulo":"Vídeo","valor":"Intel UHD Graphics 620 (integrado)"},{"rotulo":"Bateria","valor":"4 células, 68 Wh · 85% de saúde · 5h a 7h em uso de escritório"},{"rotulo":"Teclado","valor":"ABNT2 retroiluminado"},{"rotulo":"Rede","valor":"Wi-Fi 5 (ac) + Bluetooth 5.0"},{"rotulo":"Conexões","valor":"2x USB 3.1 Type-A · USB-C com DisplayPort · HDMI 1.4 · RJ-45 Gigabit · Leitor microSD · Combo P2"},{"rotulo":"Sistema","valor":"Windows 11 Pro ativado"},{"rotulo":"Peso","valor":"1.60 kg"}]'::jsonb, 'A', '["Chassi sem amassado, borrachinhas da base completas","Tela sem mancha de pressão","Limpeza interna e troca de pasta térmica feitas"]'::jsonb, 90, 6),
  ('HT-TMP214', 'acer-travelmate-p214-i5-8gb-256gb', 'notebook', 'Acer', 'TravelMate P214-52', 'seminovo', 1690, null, false, true, 'Wi-Fi 6 e HDMI 2.0 pelo menor preço da lista com tela Full HD IPS.', 'i5', 'Intel Core i5-1035G1', 8, 256, 'NVMe', 14, '1920 x 1080', 87, 1.6, '[{"rotulo":"Processador","valor":"Intel Core i5-1035G1 · 4 núcleos / 8 threads"},{"rotulo":"Clock","valor":"1.0 GHz base · 3.6 GHz turbo"},{"rotulo":"Memória","valor":"8 GB DDR4 2666 MHz"},{"rotulo":"Expansão de memória","valor":"2 slots SODIMM — 1 ocupado, expansível até 32 GB"},{"rotulo":"Armazenamento","valor":"256 GB SSD NVMe M.2"},{"rotulo":"Expansão de disco","valor":"Baia 2.5\" livre para HD adicional"},{"rotulo":"Tela","valor":"14\" 1920 x 1080 IPS · antirreflexo"},{"rotulo":"Vídeo","valor":"Intel UHD Graphics G1 (integrado)"},{"rotulo":"Bateria","valor":"3 células, 48 Wh · 87% de saúde · 6h a 7h em uso de escritório"},{"rotulo":"Teclado","valor":"ABNT2 retroiluminado"},{"rotulo":"Rede","valor":"Wi-Fi 6 (ax) + Bluetooth 5.0"},{"rotulo":"Conexões","valor":"3x USB 3.2 Type-A · USB-C · HDMI 2.0 · RJ-45 Gigabit · Combo P2"},{"rotulo":"Sistema","valor":"Windows 11 Pro ativado"},{"rotulo":"Peso","valor":"1.60 kg"}]'::jsonb, 'A', '["Aparelho de lote escolar com uso leve","Sem marca no apoio de mão","Carregador original incluso"]'::jsonb, 90, 7),
  ('HT-X1C6', 'lenovo-thinkpad-x1-carbon-6-i7-16gb-512gb', 'notebook', 'Lenovo', 'ThinkPad X1 Carbon 6ª geração', 'seminovo', 3190, 3690, true, true, '1,13 kg. O mais leve do estoque, chassi de fibra de carbono.', 'i7', 'Intel Core i7-8650U', 16, 512, 'NVMe', 14, '1920 x 1080', 82, 1.13, '[{"rotulo":"Processador","valor":"Intel Core i7-8650U · 4 núcleos / 8 threads"},{"rotulo":"Clock","valor":"1.9 GHz base · 4.2 GHz turbo"},{"rotulo":"Memória","valor":"16 GB LPDDR3 2133 MHz"},{"rotulo":"Expansão de memória","valor":"Memória soldada — não expansível"},{"rotulo":"Armazenamento","valor":"512 GB SSD NVMe M.2"},{"rotulo":"Expansão de disco","valor":"Sem baia adicional"},{"rotulo":"Tela","valor":"14\" 1920 x 1080 IPS 300 nits · antirreflexo"},{"rotulo":"Vídeo","valor":"Intel UHD Graphics 620 (integrado)"},{"rotulo":"Bateria","valor":"4 células, 57 Wh · 82% de saúde · 7h a 9h em uso de escritório"},{"rotulo":"Teclado","valor":"ABNT2 retroiluminado com TrackPoint"},{"rotulo":"Rede","valor":"Wi-Fi 5 (ac) + Bluetooth 4.2"},{"rotulo":"Conexões","valor":"2x USB 3.1 Type-A · 2x USB-C Thunderbolt 3 · HDMI 1.4 · RJ-45 via adaptador incluso · Combo P2"},{"rotulo":"Sistema","valor":"Windows 11 Pro ativado"},{"rotulo":"Peso","valor":"1.13 kg"}]'::jsonb, 'A', '["Acabamento soft touch da tampa preservado, sem descascado","Dobradiça firme, sem folga","Acompanha adaptador de rede e carregador original de 65 W"]'::jsonb, 90, 8),
  ('HT-E840G6', 'hp-elitebook-840-g6-i7-16gb-512gb', 'notebook', 'HP', 'EliteBook 840 G6', 'seminovo', 2590, null, false, true, 'Tela de 400 nits — a mais clara do estoque, boa para ambiente iluminado.', 'i7', 'Intel Core i7-8565U', 16, 512, 'NVMe', 14, '1920 x 1080', 90, 1.49, '[{"rotulo":"Processador","valor":"Intel Core i7-8565U · 4 núcleos / 8 threads"},{"rotulo":"Clock","valor":"1.8 GHz base · 4.6 GHz turbo"},{"rotulo":"Memória","valor":"16 GB DDR4 2400 MHz"},{"rotulo":"Expansão de memória","valor":"2 slots SODIMM — 2 ocupados (8+8)"},{"rotulo":"Armazenamento","valor":"512 GB SSD NVMe M.2"},{"rotulo":"Expansão de disco","valor":"Sem baia adicional"},{"rotulo":"Tela","valor":"14\" 1920 x 1080 IPS 400 nits · antirreflexo"},{"rotulo":"Vídeo","valor":"Intel UHD Graphics 620 (integrado)"},{"rotulo":"Bateria","valor":"3 células, 50 Wh · 90% de saúde · 7h a 9h em uso de escritório"},{"rotulo":"Teclado","valor":"ABNT2 retroiluminado, resistente a respingos"},{"rotulo":"Rede","valor":"Wi-Fi 5 (ac) + Bluetooth 5.0"},{"rotulo":"Conexões","valor":"2x USB 3.1 Type-A · 2x USB-C Thunderbolt 3 · HDMI 1.4 · RJ-45 Gigabit · Combo P2"},{"rotulo":"Sistema","valor":"Windows 11 Pro ativado"},{"rotulo":"Peso","valor":"1.49 kg"}]'::jsonb, 'A', '["Chassi de alumínio sem amassado","Bateria em 90% de saúde","Tampa da webcam física funcionando"]'::jsonb, 90, 9),
  ('HT-L3420', 'dell-latitude-3420-i3-8gb-256gb', 'notebook', 'Dell', 'Latitude 3420', 'seminovo', 1690, null, false, true, 'Aparelho de 2021 com bateria em 95%. Tela HD é a única concessão.', 'i3', 'Intel Core i3-1115G4', 8, 256, 'NVMe', 14, '1366 x 768', 95, 1.63, '[{"rotulo":"Processador","valor":"Intel Core i3-1115G4 · 2 núcleos / 4 threads"},{"rotulo":"Clock","valor":"3.0 GHz base · 4.1 GHz turbo"},{"rotulo":"Memória","valor":"8 GB DDR4 3200 MHz"},{"rotulo":"Expansão de memória","valor":"2 slots SODIMM — 1 ocupado, expansível até 64 GB"},{"rotulo":"Armazenamento","valor":"256 GB SSD NVMe M.2"},{"rotulo":"Expansão de disco","valor":"Baia 2.5\" livre para HD adicional"},{"rotulo":"Tela","valor":"14\" 1366 x 768 TN · antirreflexo"},{"rotulo":"Vídeo","valor":"Intel UHD Graphics (integrado)"},{"rotulo":"Bateria","valor":"3 células, 54 Wh · 95% de saúde · 7h a 8h em uso de escritório"},{"rotulo":"Teclado","valor":"ABNT2 sem retroiluminação"},{"rotulo":"Rede","valor":"Wi-Fi 6 (ax) + Bluetooth 5.1"},{"rotulo":"Conexões","valor":"2x USB 3.2 Type-A · USB-C com DisplayPort · HDMI 1.4 · RJ-45 Gigabit · Combo P2"},{"rotulo":"Sistema","valor":"Windows 11 Pro ativado"},{"rotulo":"Peso","valor":"1.63 kg"}]'::jsonb, 'A', '["Praticamente sem sinal de uso, veio de lote lacrado de contrato","Tela 1366x768 — ideal para sistema de gestão e planilha simples","Upgrade para 16 GB por R$ 210 no ato da compra"]'::jsonb, 90, 10),
  ('HT-L14G2', 'lenovo-thinkpad-l14-gen2-ryzen5-16gb-512gb', 'notebook', 'Lenovo', 'ThinkPad L14 Gen 2', 'seminovo', 2390, null, false, true, '6 núcleos e 12 threads — o mais rápido em tarefa pesada por este preço.', 'Ryzen 5', 'AMD Ryzen 5 PRO 4650U', 16, 512, 'NVMe', 14, '1920 x 1080', 89, 1.61, '[{"rotulo":"Processador","valor":"AMD Ryzen 5 PRO 4650U · 6 núcleos / 12 threads"},{"rotulo":"Clock","valor":"2.1 GHz base · 4.0 GHz turbo"},{"rotulo":"Memória","valor":"16 GB DDR4 3200 MHz"},{"rotulo":"Expansão de memória","valor":"2 slots SODIMM — 2 ocupados (8+8)"},{"rotulo":"Armazenamento","valor":"512 GB SSD NVMe M.2"},{"rotulo":"Expansão de disco","valor":"Sem baia adicional"},{"rotulo":"Tela","valor":"14\" 1920 x 1080 IPS · antirreflexo"},{"rotulo":"Vídeo","valor":"AMD Radeon Graphics (integrado)"},{"rotulo":"Bateria","valor":"3 células, 45 Wh · 89% de saúde · 8h a 10h em uso de escritório"},{"rotulo":"Teclado","valor":"ABNT2 retroiluminado com TrackPoint"},{"rotulo":"Rede","valor":"Wi-Fi 6 (ax) + Bluetooth 5.1"},{"rotulo":"Conexões","valor":"2x USB 3.2 Type-A · 2x USB-C · HDMI 2.0 · RJ-45 Gigabit · Leitor SD · Combo P2"},{"rotulo":"Sistema","valor":"Windows 11 Pro ativado"},{"rotulo":"Peso","valor":"1.61 kg"}]'::jsonb, 'A', '["Melhor escolha para quem roda máquina virtual ou edita planilha grande","Bateria em 89% de saúde","Sem marca no apoio de mão"]'::jsonb, 90, 11),
  ('HT-PC-R5', 'pc-montado-ryzen5-16gb-rtx3060', 'desktop', 'HebaTech', 'PC montado Ryzen 5 5600 + RTX 3060', 'novo', 4890, null, true, true, 'Montado e testado na bancada, com cabeamento organizado e sistema instalado. Roda jogo em 1080p e aguenta edição de vídeo.', null, null, null, null, null, null, null, null, null, '[{"rotulo":"Processador","valor":"AMD Ryzen 5 5600 · 6 núcleos / 12 threads · até 4.4 GHz"},{"rotulo":"Placa de vídeo","valor":"NVIDIA GeForce RTX 3060 12 GB"},{"rotulo":"Memória","valor":"16 GB DDR4 3200 MHz (2x8, dual channel)"},{"rotulo":"Armazenamento","valor":"SSD NVMe 1 TB"},{"rotulo":"Placa-mãe","valor":"B550M com M.2 PCIe 4.0"},{"rotulo":"Fonte","valor":"650 W 80 Plus Bronze"},{"rotulo":"Refrigeração","valor":"Water cooler 240 mm"},{"rotulo":"Gabinete","valor":"Mid tower com lateral de vidro e 4 fans"},{"rotulo":"Sistema","valor":"Windows 11 Pro ativado"},{"rotulo":"Garantia","valor":"12 meses nas peças, 90 dias na montagem"}]'::jsonb, null, '["Cabeamento feito por trás do berço, sem fio solto na área de fluxo","Teste de estresse de 2h em CPU e GPU antes da entrega","Configuração pode ser ajustada — fale a sua faixa de preço"]'::jsonb, 365, 12),
  ('HT-PC-I5', 'pc-escritorio-i5-8gb-ssd480', 'desktop', 'HebaTech', 'PC de escritório i5 + SSD 480 GB', 'seminovo', 1290, null, false, true, 'Máquina de escritório montada com peça revisada. Liga rápido, roda sistema de gestão, planilha e navegador com folga.', null, null, null, null, null, null, null, null, null, '[{"rotulo":"Processador","valor":"Intel Core i5-4590 · 4 núcleos · até 3.7 GHz"},{"rotulo":"Memória","valor":"8 GB DDR3 1600 MHz"},{"rotulo":"Armazenamento","valor":"SSD SATA 480 GB"},{"rotulo":"Vídeo","valor":"Intel HD Graphics 4600 (integrado)"},{"rotulo":"Saídas de vídeo","valor":"HDMI + VGA + DVI"},{"rotulo":"Rede","valor":"Ethernet Gigabit"},{"rotulo":"Fonte","valor":"400 W real"},{"rotulo":"Sistema","valor":"Windows 11 Pro ativado"}]'::jsonb, 'B', '["Gabinete com riscos de uso, interior limpo e sem oxidação","Não acompanha monitor, teclado e mouse — veja os itens avulsos","Ideal para ponto de venda, recepção e escritório"]'::jsonb, 90, 13),
  ('HT-MON-P2419', 'monitor-dell-p2419h-24-full-hd-ips', 'monitor', 'Dell', 'Monitor P2419H 24" Full HD IPS', 'seminovo', 549, 690, true, true, 'Monitor corporativo com borda fina, base com ajuste de altura e rotação. Painel IPS, bom para trabalhar o dia inteiro.', null, null, null, null, null, 24, '1920 x 1080', null, null, '[{"rotulo":"Tela","valor":"23,8\" IPS · 1920 x 1080 · antirreflexo"},{"rotulo":"Taxa de atualização","valor":"60 Hz"},{"rotulo":"Ajustes da base","valor":"Altura, inclinação, giro e rotação para retrato"},{"rotulo":"Conexões","valor":"HDMI · DisplayPort · VGA · 4x USB 3.0"},{"rotulo":"Suporte VESA","valor":"100 x 100 mm"},{"rotulo":"Acompanha","valor":"Cabo de força e cabo DisplayPort"}]'::jsonb, 'A', '["Sem pixel morto e sem mancha de retroiluminação","Base original inclusa, trava de encaixe funcionando","Lote corporativo com pouco uso"]'::jsonb, 90, 14),
  ('HT-SSD-1TB', 'ssd-nvme-1tb-instalado', 'peca', 'Kingston', 'SSD NVMe 1 TB NV3 — com instalação', 'novo', 449, null, false, true, 'Peça nova com nota fiscal. O preço já inclui instalação, clonagem do disco atual e conferência dos seus arquivos na loja.', null, null, null, null, null, null, null, null, null, '[{"rotulo":"Capacidade","valor":"1 TB"},{"rotulo":"Interface","valor":"M.2 NVMe PCIe 4.0"},{"rotulo":"Leitura sequencial","valor":"até 6000 MB/s"},{"rotulo":"Gravação sequencial","valor":"até 4000 MB/s"},{"rotulo":"Compatibilidade","valor":"Notebook e desktop com slot M.2 PCIe"},{"rotulo":"Serviço incluso","valor":"Instalação, clonagem do sistema e teste"},{"rotulo":"Garantia","valor":"12 meses do fabricante + 90 dias da instalação"}]'::jsonb, null, '["Confirmamos a compatibilidade do seu aparelho antes de fechar","Clonagem preserva Windows, programas e arquivos como estão","Se preferir, instalamos limpo com o Windows do zero"]'::jsonb, 365, 15),
  ('HT-MEM-8GB', 'memoria-ddr4-8gb-sodimm-instalada', 'peca', 'Crucial', 'Memória DDR4 8 GB SODIMM — com instalação', 'novo', 189, null, false, true, 'Upgrade mais barato que existe para tirar um notebook do sufoco. Instalação e teste de memória inclusos.', null, null, null, null, null, null, null, null, null, '[{"rotulo":"Capacidade","valor":"8 GB"},{"rotulo":"Tipo","valor":"DDR4 SODIMM 3200 MHz (compatível com 2400 e 2666)"},{"rotulo":"Aplicação","valor":"Notebook e all in one"},{"rotulo":"Serviço incluso","valor":"Instalação e teste de memória na bancada"},{"rotulo":"Garantia","valor":"Vitalícia do fabricante"}]'::jsonb, null, '["Verificamos antes se o seu aparelho tem slot livre","Em máquina com memória soldada, conferimos o limite suportado"]'::jsonb, 365, 16),
  ('HT-DOCK-USBC', 'dock-station-usb-c-dual-hdmi', 'acessorio', 'Lenovo', 'Dock Station USB-C com dual HDMI', 'seminovo', 429, null, false, true, 'Um cabo só liga o notebook a dois monitores, rede, teclado e mouse. Carrega o aparelho pelo mesmo cabo.', null, null, null, null, null, null, null, null, null, '[{"rotulo":"Conexão com o notebook","valor":"USB-C único, com Power Delivery até 65 W"},{"rotulo":"Saídas de vídeo","valor":"2x HDMI (até 1920 x 1080 a 60 Hz cada)"},{"rotulo":"Portas USB","valor":"3x USB 3.0 Type-A · 1x USB-C de dados"},{"rotulo":"Rede","valor":"Ethernet Gigabit"},{"rotulo":"Áudio","valor":"Combo P2"},{"rotulo":"Compatibilidade","valor":"Notebook com USB-C que suporte DisplayPort Alt Mode"}]'::jsonb, 'A', '["Testada com dois monitores ligados ao mesmo tempo","Acompanha fonte original","Confirme na loja se o seu notebook suporta vídeo pela USB-C"]'::jsonb, 90, 17),
  ('HT-KIT-CORP', 'kit-teclado-mouse-com-fio-abnt2', 'periferico', 'Logitech', 'Kit teclado e mouse com fio ABNT2', 'novo', 129, null, false, true, 'Kit novo para montar posto de trabalho. Layout ABNT2 com ç e acento, plug and play.', null, null, null, null, null, null, null, null, null, '[{"rotulo":"Teclado","valor":"ABNT2 com teclado numérico · resistente a respingos"},{"rotulo":"Mouse","valor":"Óptico 1000 DPI, 3 botões com roda"},{"rotulo":"Conexão","valor":"USB, sem necessidade de driver"},{"rotulo":"Comprimento do cabo","valor":"1,5 m"},{"rotulo":"Garantia","valor":"12 meses do fabricante"}]'::jsonb, null, '[]'::jsonb, 365, 18)
on conflict (codigo) do update set
    slug = excluded.slug,
    categoria = excluded.categoria,
    marca = excluded.marca,
    modelo = excluded.modelo,
    condicao = excluded.condicao,
    preco = excluded.preco,
    preco_referencia = excluded.preco_referencia,
    destaque = excluded.destaque,
    disponivel = excluded.disponivel,
    resumo = excluded.resumo,
    cpu_familia = excluded.cpu_familia,
    cpu_nome = excluded.cpu_nome,
    ram_gb = excluded.ram_gb,
    armazenamento_gb = excluded.armazenamento_gb,
    armazenamento_tipo = excluded.armazenamento_tipo,
    tela_polegadas = excluded.tela_polegadas,
    tela_resolucao = excluded.tela_resolucao,
    bateria_saude = excluded.bateria_saude,
    peso_kg = excluded.peso_kg,
    ficha = excluded.ficha,
    estado_grau = excluded.estado_grau,
    estado_observacoes = excluded.estado_observacoes,
    garantia_dias = excluded.garantia_dias,
    ordem = excluded.ordem
;

-- ── 3 planos de manutenção mensal ──
insert into public.planos_manutencao (codigo, nome, faixa, preco_mensal, visitas, destaque, ativo, inclui, ordem)
values
  ('MP-01', 'Essencial', 'Até 5 máquinas', 390, '1 visita por mês', false, true, '["Visita técnica programada, 1x por mês","Suporte remoto no horário comercial","Limpeza e revisão preventiva das máquinas","Atualização de Windows e antivírus","Inventário de equipamento e licença","Mão de obra de reparo com 20% de desconto"]'::jsonb, 0),
  ('MP-02', 'Operação', 'De 6 a 15 máquinas', 790, '2 visitas por mês', true, true, '["Tudo do plano Essencial","Visita técnica programada, 2x por mês","Chamado remoto ilimitado no horário comercial","Rotina de backup com teste de restauração trimestral","Monitoramento de disco e de saúde de bateria","Máquina reserva durante reparo que passe de 48h","Mão de obra de reparo inclusa no contrato"]'::jsonb, 1),
  ('MP-03', 'Completo', 'De 16 a 30 máquinas', null, 'Visita semanal', false, true, '["Tudo do plano Operação","Visita técnica semanal com técnico fixo","Atendimento emergencial em até 4h úteis","Gestão de rede, cabeamento e Wi-Fi","Padronização de imagem do Windows","Plano de reposição de máquina em 12 e 24 meses","Relatório mensal dos equipamentos por e-mail"]'::jsonb, 2)
on conflict (codigo) do update set
    nome = excluded.nome,
    faixa = excluded.faixa,
    preco_mensal = excluded.preco_mensal,
    visitas = excluded.visitas,
    destaque = excluded.destaque,
    ativo = excluded.ativo,
    inclui = excluded.inclui,
    ordem = excluded.ordem
;

-- ── Regras do contrato de manutenção ──
-- Só entra se ainda não existir, para não apagar o que foi editado no painel.
insert into public.configuracoes (chave, valor)
values ('manutencao_regras', '[{"titulo":"Sem fidelidade","texto":"Contrato mensal. Você cancela avisando com 30 dias."},{"titulo":"Peça à parte","texto":"A mensalidade cobre mão de obra e visita. Peça é orçada e aprovada por você."},{"titulo":"Nota fiscal","texto":"Emitida todo mês, com o serviço discriminado para lançar no contábil."},{"titulo":"Fora de Sete Lagoas","texto":"Atendemos a região com taxa de deslocamento fechada no contrato."}]'::jsonb)
on conflict (chave) do nothing;
